package by.samsolution.pharmacy.entity;

public enum PackingForm {
    TABLET, POWDER, CAPSULE, DRAGEES, GRANULE, CARAMEL, OINTMENT, CREAM, PASTE, GEL, SOLUTION, TINCTURE, SUSPENSION, EMULSION,
    DROP, SYRUP, POTION, AEROSOL;
}
